### ISSUE TITLE
reddit v1

### ISSUE THREAD

**Issue by vindarel** [azzamsa/awesome-cl-software#15]
The Lisp code of reddit v1 was recently released. https://www.reddit.com/r/programming/comments/883vzs/old_reddit_source_code/
https://github.com/reddit-archive/reddit1.0/

where shall we put it ?

regards

**Comment by azzamsa** [comment]
I put Kindista which has same category as Reddit in "Other" section.

To make these active project visible. we have to put it at the top of every section and put deprecated project at see also, as we have agreed.

I think it's nice to put Reddit below Kindista.

**Comment by azzamsa** [comment]
@vindarel What is your opinion ?

What if we add `Social news` section. and put reddit below that ?

**Comment by vindarel** [comment]
+1 good idea

**Comment by azzamsa** [comment]
I use [wikipedia](https://en.wikipedia.org/wiki/Reddit)  `Type of site`

```
Type of site : Social news and -media aggregation
```
I think we should move Kindista out of `Other` section. It's still actively developed and should be easy to spot for any visitor here.

Do you have any ideas where to put Kindista ?
