### ISSUE TITLE
Add :star: for actively maintained and most starred app

### ISSUE THREAD

**Issue by azzamsa** [azzamsa/awesome-cl-software#21]
I want to add :star: for app that actively maintained and most starred app.

E.g Kindista, Lem, Mezzano.

Inspired from https://github.com/CodyReichert/awesome-cl/blob/master/README.md

@vindarel what is your opinion ?

**Comment by vindarel** [comment]
I think it's a good idea, it was a requested and appreciated change on the awesome-list.

**Comment by azzamsa** [comment]
After thinking for while. I decided to avoid :star: based list. I decide to keep 'master' branch curated, and make 'complete-list' branch for complrte/exhausting list.

**Comment by vindarel** [comment]
curating is good, but nobody will see another branch than master. Could be for historical purposes.

**Comment by azzamsa** [comment]
it's very hard decesion to remove them/ move to complete-list branch. But I don't want this list full of unmaintained package and abandoned project from 2003. I want to keep that app if no other app exist in certain section, but turns out there are another app that actively maintained and get more attention.

So I just dropped them to another branch for historical purpose.

**Comment by azzamsa** [comment]
I saw other awesome-list, they just drop unmaintained packages, since it become messy/huge to add all of them.

**Comment by azzamsa** [comment]
I would like to do that. But I am really worried, I don't want jealousy from each other. I think **sorting** them based on stargazer/popularity is enough. 

I already sorted them based on stargazers.

**Comment by vindarel** [comment]
this is good indeed. I noticed that some sections don't have a "strong" software though.
