### ISSUE TITLE
Web frameworks / web devel

### ISSUE THREAD

**Issue by defunkydrummer** [azzamsa/awesome-cl-software#8]
Hi Azzamsa, 

First of all, thanks for this list. 

I would like to suggest you to add a section on web development. Suggestion for projects in this category would be the following web development tools:

- Lucerne (complete web framework)
- Caveman2 (complete web framework)
- Clack and Lack (building blocks for web applications, used by all the above)
- Reblocks (further advancement of Weblocks, a complete web framework)

and also, if not included above:
- Parenscript (Common Lisp subset that can be compiled to javascript)
- JSCL (Common Lisp subset implementation that is self-hosted in javascript)

I'd also want to add my own "minimal quick&dirty zero-learning-curve web framework", Ninglex, but i don't think it's an "awesome" tool, just a quick&dirty lib.

**Comment by defunkydrummer** [comment]
... and forgot to include Hunchentoot, the most famous web server for Common Lisp, 
plus:
teepeedee2, which once was *the fastest dynamic web server* in **any** programming language, bar none.

**Comment by defunkydrummer** [comment]
Shinmera's "Radiance" must be awesome as well:

**Comment by azzamsa** [comment]
Hi defunkydrummer.

Thank you for your interest in this repository.
But the aim of this repository is to list all awesome "application software" built with Common Lisp . For non application software (library, tools, etc), we have another repository, [awesome-cl](https://github.com/CodyReichert/awesome-cl). And some of your suggestion already there :)

Happy hacking.
